image: Visual Studio 2017
configuration: Release

install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

before_build:
  - nuget restore src\TinyLittleMvvm.sln
  - ps: gitversion /l console /output buildserver

build:
  project: src\TinyLittleMvvm.sln

for:

# create nuget package only for develop and master branch
-
  branches:
    only:
      - master
      - develop

  after_build:
    - cmd: ECHO nuget pack src\TinyLittleMvvm\TinyLittleMvvm.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
    - cmd: nuget pack src\TinyLittleMvvm\TinyLittleMvvm.csproj -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
    - cmd: appveyor PushArtifact "TinyLittleMvvm.%GitVersion_NuGetVersion%.nupkg"