name: Build

on:
  push:
  pull_request:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    name: Build

    if: "!contains(github.event.head_commit.message, 'skip-ci')"

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
  
      - name: Restore dependencies
        run: |
          cd src
          dotnet restore
          dotnet restore Templates\templatepack.csproj
  
      - name: Build
        run: |
          cd src
          dotnet build --configuration Release --no-restore
          dotnet build Templates\templatepack.csproj --configuration Release --no-restore
  
      - name: Pack
        run: |
          cd src
          dotnet pack TinyLittleMvvm/TinyLittleMvvm.csproj --configuration Release --no-build --output .
          dotnet pack TinyLittleMvvm.MahAppsMetro/TinyLittleMvvm.MahAppsMetro.csproj --configuration Release --no-build --output .
          dotnet pack Templates\templatepack.csproj --configuration Release --no-build --output .
  
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nupkg
          path: ./src/*.nupkg
      
      - name: Publish to GitHub
        run: |
          cd src
          dotnet nuget push *.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --no-symbols --skip-duplicate
      
      - name: Publish to NuGet
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
        run: |
          cd src
          dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --no-symbols --skip-duplicate
